### PR TITLE
Build with sbt version 1.0.2

### PR DESCRIPTION
**Pull request by jonas**
Also adds to tests to track the minimum required version of sbt 0.13 and 1.0. For 0.13 we require 0.13.10 since 0.13.9 fails with:

```
[info] java.lang.NoClassDefFoundError: sbt/TrackLevel
[info] 	at java.lang.Class.forName0(Native Method)
[info] 	at java.lang.Class.forName(Class.java:348)
[info] 	at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:14)
[info] 	at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
[info] 	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
[info] 	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
[info] 	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
[info] 	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
[info] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
[info] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
[info] 	at scala.collection.immutable.Stream.foreach(Stream.scala:548)
[info] 	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
[info] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
[info] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
[info] 	at scala.collection.TraversableLike$class.to(TraversableLike.scala:629)
[info] 	at scala.collection.AbstractTraversable.to(Traversable.scala:105)
[info] 	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)
[info] 	at scala.collection.AbstractTraversable.toList(Traversable.scala:105)
[info] 	at scala.collection.immutable.List.$plus$plus(List.scala:193)
[info] 	at sbt.PluginDiscovery$.discoverAll(PluginDiscovery.scala:38)
```

### CODE REVIEW

**Comment by jonas** [comment]
\o/
